import { useParams } from 'react-router-dom'
import { useGetDoctorReportQuery } from '../../shared/api/api'
import { AuraSymptomsSection } from './components/DoctorReport/AuraSymptomsSection'
import { ClinicalFlags } from './components/DoctorReport/ClinicalFlags'
import { ClinicalSummary } from './components/DoctorReport/ClinicalSummary'
import { DailyTimeline } from './components/DoctorReport/DailyTimeline'
import { FrequencyChart } from './components/DoctorReport/FrequencyChart'
import { LocationQuality } from './components/DoctorReport/LocationQuality'
import { MigraineProfile } from './components/DoctorReport/MigraineProfile'
import { PatternAnalysis } from './components/DoctorReport/PatternAnalysis'
import { ReportHeader } from './components/DoctorReport/ReportHeader'
import { SeverityChart } from './components/DoctorReport/SeverityChart'
import { TreatmentEfficacy } from './components/DoctorReport/TreatmentEfficacy'
import { TreatmentFailures } from './components/DoctorReport/TreatmentFailures'
import { TriggerCorrelation } from './components/DoctorReport/TriggerCorrelation'
import './styles/health.css'

/**
 * Public, token-gated doctor report. Routed outside `ProtectedRoute` so
 * a clinician on their own laptop / phone can open the QR-code URL
 * without ever signing in.
 *
 * The query string token is the only credential — `useGetDoctorReportQuery`
 * lives on `publicApi` (the anonymous RTK Query slice), so no Authorization
 * header is sent.
 *
 * Layout follows `docs/mocks/doctor-report-mock.html` top-to-bottom.
 * Every block is its own component under `DoctorReport/` so they can be
 * exercised in isolation and the page itself is just orchestration.
 */
export function PublicReportPage() {
  const { token } = useParams<{ token: string }>()
  const { data, isLoading, error } = useGetDoctorReportQuery(token ?? '', {
    skip: !token,
  })

  if (!token) {
    return <ErrorView message="ลิงก์นี้ไม่ถูกต้อง" />
  }

  if (isLoading || (!data && !error)) {
    return <LoadingView />
  }

  if (error) {
    // RTK Query surfaces HTTP errors via `FetchBaseQueryError` with a
    // `status` field. Map 401/403/404/410 to user-friendly Thai copy.
    const status =
      typeof error === 'object' && error && 'status' in error
        ? (error as { status: number | string }).status
        : null
    if (status === 401 || status === 403) {
      return <ErrorView message="ลิงก์นี้ถูกเพิกถอนแล้ว" />
    }
    if (status === 404 || status === 410) {
      return <ErrorView message="ไม่พบรายงาน หรือลิงก์หมดอายุ" />
    }
    return <ErrorView message="เกิดข้อผิดพลาด ลองรีเฟรชหน้า" />
  }

  if (!data) {
    return <LoadingView />
  }

  return (
    <div className="health-report-page">
      <div className="health-report-container">
        <PrintButton />
        <ReportHeader report={data} />
        <ClinicalFlags flags={data.clinicalFlags} />
        <MigraineProfile
          summary={data.summary}
          durationDays={data.durationDays}
          days={data.days}
        />
        <div className="health-report-card">
          <h2 className="health-report-h2">
            📊 Attack frequency & severity ({data.durationDays} วัน)
          </h2>
          <FrequencyChart days={data.days} />
          <SeverityChart days={data.days} />
        </div>
        <AuraSymptomsSection days={data.days} summary={data.summary} />
        <LocationQuality days={data.days} />
        <TriggerCorrelation
          triggers={data.triggerCorrelations}
          totalAttacks={data.summary.totalAttacks}
        />
        <TreatmentEfficacy items={data.treatmentEfficacy} />
        <PatternAnalysis
          patterns={data.patterns}
          totalAttacks={data.summary.totalAttacks}
        />
        <TreatmentFailures events={data.noDrugEvents} />
        <DailyTimeline days={data.days} />
        <ClinicalSummary report={data} />
        <div className="health-report-footer">
          Generated by MenuNest Health Tracker • Migraine Report v1.0
        </div>
      </div>
    </div>
  )
}

function PrintButton() {
  // Doctors save reports as PDF for EHR uploads via the browser's print
  // dialog. The print stylesheet (see health.css `@media print`) strips
  // shadows + the button itself.
  return (
    <button
      type="button"
      className="health-report-print-btn"
      onClick={() => window.print()}
    >
      🖨️ Print / Save PDF
    </button>
  )
}

function LoadingView() {
  return (
    <div className="health-report-page">
      <div className="health-report-container">
        <div className="health-report-loading">กำลังโหลดรายงาน...</div>
      </div>
    </div>
  )
}

function ErrorView({ message }: { message: string }) {
  return (
    <div className="health-report-page">
      <div className="health-report-container">
        <div className="health-report-error">
          <div className="health-report-error-icon">⚠️</div>
          <div className="health-report-error-text">{message}</div>
        </div>
      </div>
    </div>
  )
}
